#!/usr/bin/env python3
"""Regenerate the master index of the X-Ways template collection.

Scans templates/ for .tpl (and .txt) files with a template header, merges
provenance (templates/imported/PROVENANCE.json) and curation notes
(templates/curation.json), and writes templates/INDEX.md.

The index answers two questions before any reversing starts:
  - is this structure already covered by a working template (Phase 0 prior
    art), and how far can that template be trusted?
  - which structures are known to matter but have no template yet (the
    to-make list, fed from the galleries in references/format-galleries.md)?

The INDEX.md is generated; edit curation.json, not the output.

Usage:
  tpl_index.py                 # print summary, check INDEX.md is current
  tpl_index.py --write         # regenerate templates/INDEX.md
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TDIR = os.path.join(ROOT, "templates")

STATUSES = ("complete", "partial", "unreviewed", "draft")


def parse_header(path):
    """Pull title, description, applies_to, requires from a template file."""
    info = {"title": "", "desc": "", "applies_to": "", "requires": [],
            "read_only": False, "fields": 0}
    try:
        with open(path, encoding="utf-8-sig", errors="replace") as fh:
            text = fh.read()
    except OSError:
        return None
    if not re.search(r"(?im)^\s*template\s", text):
        return None
    body = False
    for line in text.splitlines():
        line = re.sub(r'//(?=(?:[^"]*"[^"]*")*[^"]*$).*', "", line).strip()
        if not line:
            continue
        toks = re.findall(r'"[^"]*"|[^"\s]+', line)
        head = toks[0].lower()
        if head == "begin":
            body = True
        if body:
            # count declarations loosely: lines starting with a known-looking
            # type keyword; good enough for an index size hint
            if re.match(r"(?i)^(u?int|hex|char|string|zstring|boole|float|"
                        r"double|single|longdouble|binary|guid|.*datetime|"
                        r"filetime|time_t|uint_flex)", head):
                info["fields"] += 1
            continue
        if head == "template" and len(toks) > 1:
            info["title"] = toks[1].strip('"')
        elif head == "description" and len(toks) > 1:
            info["desc"] = toks[1].strip('"')
        elif head in ("applies_to", "appliesto") and len(toks) > 1:
            info["applies_to"] = toks[1]
        elif head == "requires" and len(toks) > 2:
            info["requires"].append(
                f"{toks[1]}:{toks[2].strip(chr(34)).replace(' ', '')}")
        elif head == "read-only":
            info["read_only"] = True
    return info


def scan():
    entries = []
    for dirpath, dirnames, filenames in os.walk(TDIR):
        dirnames.sort()
        for name in sorted(filenames):
            if not name.lower().endswith((".tpl", ".txt")):
                continue
            path = os.path.join(dirpath, name)
            info = parse_header(path)
            if info is None:
                continue
            rel = os.path.relpath(path, TDIR).replace("\\", "/")
            info["path"] = rel
            entries.append(info)
    return entries


def load_json(path):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    return {}


def render(entries, prov, cur):
    overrides = cur.get("templates", {})
    lines = [
        "# X-Ways template collection — master index",
        "",
        "Generated by `scripts/tpl_index.py --write`. Do not edit by hand;",
        "record judgements in `templates/curation.json` and regenerate.",
        "",
        "Status meanings: **complete** = reviewed, covers the structure as",
        "documented; **partial** = works but known gaps (see notes);",
        "**draft** = generated from our own findings, still under test;",
        "**unreviewed** = imported, not yet assessed against a reference.",
        "",
        f"{len(entries)} templates.",
        "",
    ]
    bydir = {}
    for e in entries:
        d = os.path.dirname(e["path"])
        bydir.setdefault(d, []).append(e)
    for d in sorted(bydir):
        lines.append(f"## {d}/")
        lines.append("")
        lines.append("| Template | Title | Applies to | Requires "
                     "| Contributor | Status | Notes |")
        lines.append("|---|---|---|---|---|---|---|")
        for e in bydir[d]:
            key = e["path"]
            # provenance keys are relative to imported/
            pkey = key[len("imported/"):] if key.startswith("imported/") \
                else key
            p = prov.get(pkey, {})
            o = overrides.get(pkey, overrides.get(key, {}))
            status = o.get("status",
                           "draft" if key.startswith("own/")
                           else "unreviewed")
            if status not in STATUSES:
                raise SystemExit(f"curation.json: bad status {status!r} "
                                 f"for {pkey}")
            notes = o.get("notes", "")
            req = " ".join(e["requires"]) or "—"
            fname = os.path.basename(key)
            lines.append(
                f"| {fname} | {e['title']} | {e['applies_to'] or '—'} "
                f"| {req} | {p.get('contributor', '—')} | {status} "
                f"| {notes} |")
        lines.append("")
    wanted = cur.get("wanted", [])
    if wanted:
        lines.append("## Known structures with no template yet")
        lines.append("")
        lines.append("Fed from the galleries in "
                     "`references/format-galleries.md`; make these with "
                     "`tplgen.py` from documented layouts rather than "
                     "reversing them fresh.")
        lines.append("")
        lines.append("| Structure | Where documented | Priority | Notes |")
        lines.append("|---|---|---|---|")
        for w in wanted:
            lines.append(f"| {w['structure']} | {w['documented']} "
                         f"| {w.get('priority', '')} | {w.get('notes', '')} |")
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Regenerate templates/INDEX.md")
    ap.add_argument("--write", action="store_true",
                    help="write INDEX.md (default: check only)")
    args = ap.parse_args()

    entries = scan()
    prov = load_json(os.path.join(TDIR, "imported", "PROVENANCE.json"))
    cur = load_json(os.path.join(TDIR, "curation.json"))
    # the imported files are local-only (not redistributed); refuse to
    # regenerate an index that would silently lose their 100+ rows just
    # because the fetch has not been run in this checkout
    absent = [k for k in prov
              if not os.path.exists(os.path.join(TDIR, "imported",
                                                 *k.split("/")))]
    if absent:
        print(f"{len(absent)} templates listed in PROVENANCE.json are not "
              f"present locally; run: python templates/fetch_templates.py")
        sys.exit(1)
    out = render(entries, prov, cur)
    index_path = os.path.join(TDIR, "INDEX.md")
    statuses = {}
    overrides = cur.get("templates", {})
    for e in entries:
        pkey = e["path"][len("imported/"):] \
            if e["path"].startswith("imported/") else e["path"]
        o = overrides.get(pkey, {})
        s = o.get("status",
                  "draft" if e["path"].startswith("own/") else "unreviewed")
        statuses[s] = statuses.get(s, 0) + 1
    print(f"{len(entries)} templates: " +
          ", ".join(f"{v} {k}" for k, v in sorted(statuses.items())))
    # orphaned curation entries mask typos silently -- surface them
    known = set()
    for e in entries:
        known.add(e["path"])
        if e["path"].startswith("imported/"):
            known.add(e["path"][len("imported/"):])
    for k in overrides:
        if k not in known:
            print(f"warning: curation.json entry matches no template: {k}")
    if args.write:
        with open(index_path, "w", encoding="utf-8") as fh:
            fh.write(out)
        print(f"wrote {os.path.relpath(index_path, ROOT)}")
    else:
        current = ""
        if os.path.exists(index_path):
            with open(index_path, encoding="utf-8") as fh:
                current = fh.read()
        if current == out:
            print("INDEX.md is current")
        else:
            print("INDEX.md is stale; run with --write")
            sys.exit(1)


if __name__ == "__main__":
    main()
