template "EVTX Chunk Header"
description "Windows XML Event Log chunk header (512 bytes of a 65536-byte chunk)"

// Generated by tplgen.py (binary-format-recon).
// Field statuses: established = survived a controlled-change test; inferred =
// consistent with the corpus but unproven; speculative = hypothesis only;
// unknown = bounded but undetermined. See the hypothesis ledger for evidence.
// Version scope: format 3.2 (Win10 2004+); verified on 6 logs / 278 chunks

applies_to file
requires 0x0 "456C6643686E6B00"
read-only

begin
    char[8] Signature                       // established; ElfChnk + NUL
    int64 "First event record number"       // established
    int64 "Last event record number"        // established; all-FF when chunk empty
    int64 "First event record identifier"   // established
    int64 "Last event record identifier"    // established
    uint32 "Header size"                    // established; 128
    uint32 "Last event record data offset"  // established
    uint32 "Free space offset"              // established
    uint32 "Event records CRC-32"           // established; covers 512..free space offset; verified
    hex 64 "unknown +0x38"
    uint32 "Unknown +0x78"                  // unknown; =1 in every chunk sampled; libyal suggests flags
    uint32 "Chunk CRC-32"                   // established; covers 0..120 PLUS 128..512; verified
    hex 256 "Common string offset array"    // inferred; 64 x uint32 per libyal; not independently tested
    hex 128 "Template pointer array"        // inferred; 32 x uint32 per libyal; not independently tested
end
