template "EVTX File Header"
description "Windows XML Event Log file header (first 4096 bytes)"

// Generated by tplgen.py (binary-format-recon).
// Field statuses: established = survived a controlled-change test; inferred =
// consistent with the corpus but unproven; speculative = hypothesis only;
// unknown = bounded but undetermined. See the hypothesis ledger for evidence.
// Version scope: format 3.2 (Win10 2004+); verified on 6 logs / 278 chunks

applies_to file
requires 0x0 "456C6646696C6500"
read-only

begin
    char[8] Signature                       // established; ElfFile + NUL
    int64 "First chunk number"              // established
    int64 "Last chunk number"               // established
    int64 "Next record identifier"          // established
    uint32 "Header size"                    // established; 128 in all samples
    uint16 "Minor version"                  // established; minor precedes major
    uint16 "Major version"                  // established
    uint16 "Header block size"              // established; 4096; imported template misreads at +41
    uint16 "Number of chunks"               // established; count of chunks IN USE (ElfChnk present), not allocated capacity; verified 6/6 vs signature count. Allocated may be larger - the difference is slack
    hex 76 "unknown +0x2C"
    uint32 "File flags"                     // established; 1=dirty 2=full
    uint32 "CRC-32"                         // established; covers bytes 0..120; verified 6/6
    hex 3968 "unknown +0x80"                // unknown; empty in all samples
end
